### ISSUE TITLE
Keystroke conflict

### ISSUE THREAD

**Issue by xi** [xi/a11y-outline#1]
Send in via mail:

> Your keystroke to activate the dialogue is Ctrl+7. In Windows, with
   Firefox 57, that keystroke not only opens the dialogue but moves focus to
   another browser tab (where I have multiple tabs open). Is there a way to
   change the keyboard shortcut?

**Comment by xi** [comment]
I chose that keystroke to mimic NVDA's NVDA+F7 shortcut for the same functionality. It seems like firefox does not yet have a UI to change the shortcuts ([related bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384)).

Do you have a suggestion which key combination should be used instead?

**Comment by mathieupigeon** [comment]
Same issue here on Mac. CTRL/CMD-ALT-7 might be a better default. However, any hard-coded shortcut is always going to conflict with the browser, an extension or the OS.

On Mac, the best solution would be to have a menu entry for the extension, as the OS offers a preference to remap menu item keys. However, I don't think this is available on Linux or Windows. A more cross-platform solution would be to allow editing the shortcut from the extension's preferences.

**Comment by xi** [comment]
> A more cross-platform solution would be to allow editing the shortcut from the extension's preferences.

I will not implement preferences because that would add a huge amount of complexity to this simple extension. I also believe that providing this kind of setting should be the job of the browser.

> CTRL/CMD-ALT-7 might be a better default

unfortunately, this is not supported by the web extension API. The available modifiers are:

- ctrl
- ctrl-shift
- alt
- alt-shift

I am leaning towards ctrl-shift-7. Any good reasons against that?

**Comment by mathieupigeon** [comment]
Fully agree that adding preferences in the extension seems like a lot of work. As far as I’m concerned, CTRL (I believe it automatically maps to CMD on macOS) + SHIFT + 7 seems fine. 

The toolbar icon is probably a sufficient workaround for any eventual extension with the same shortcut.
