### ISSUE TITLE
Idea: navigate through <form> elements

### ISSUE THREAD

**Issue by nu111** [xi/a11y-outline#12]
Hi, first of all: I love your extension, is so useful for a11y development!

I don't not about other screen-readers, but I now that [Orca supports navigation through `<form>` elements](https://help.gnome.org/users/orca/stable/commands_structural_navigation.html.en#forms).

It would be great to have it in your addon!

**Comment by xi** [comment]
This sounds like a good idea and easy enough to do. NVDA also added support for form fields and buttons a while back (https://github.com/nvaccess/nvda/pull/6131; [Screenshot](https://user-images.githubusercontent.com/121939/58956489-560c4680-8796-11e9-9a78-9f4487e568b5.png)).

But just to be sure: You are asking about `<form>` elements, but the Orca documentation you linked is about form fields and buttons. Which of these is this request about specifically?

**Comment by nu111** [comment]
Hi Xi!

> But just to be sure: You are asking about <form> elements, but the Orca documentation you linked is about form fields and buttons. Which of these is this request about specifically?

oh my! I was sure that Orca had a way to navigate through `<form>` tags, but I was wrong!

I think that the best thing is to follow NVDA, adding form fields navigation (and eventually buttons navigation?).

**Comment by xi** [comment]
By the way: Forms that have an accessible name (`aria-labelledby` or `aria-label` ) get the `form` role and show up in the landmark navigation.

**Comment by xi** [comment]
Done. I will probably do a release tomorrow.

**Comment by xi** [comment]
Took a bit longer, bit 2.2.0 is now available.
