### ISSUE TITLE
This awesome tool does not "see" into iFrames

### ISSUE THREAD

**Issue by wittjeff** [xi/a11y-outline#13]
The tool skips over iframed content. In some contexts (like learning management systems), iframed content is important or of the essence. Adding support for iframed content integration for the browser extension version (it's not possible for bookmarklet) would involve tweaking the manifest to get the right permissions, and some between-frame communication. My team believes we can do this work and would like to volunteer to do it and submit a PR.

**Comment by xi** [comment]
I would be happy to accept a PR about this. I reopened the old issue (#11) so we can keep the discussion in a single place.
