### ISSUE TITLE
Small font size with sites using html { font-size: 62.5%; }

### ISSUE THREAD

**Issue by PhilippeVay** [xi/a11y-outline#4]
… which are countless doing:

```
html {
  font-size: 62.5%;
}

body {
  font-size: 1.6rem;
}
```

because it's then really easy to use rem or em unit by thinking in pixels and having to divide by 10 and not having to use  a calc or a mixin in a preprocessor.

The extension sets `body>dialog` to 0.9rem thus gives 9px like in our site https://www.alsacreations.com (screenshot below):

![screenshot of alsacreations.com with extension enabled showing very small text](https://user-images.githubusercontent.com/534395/35398172-9605cb98-01f1-11e8-9895-4ef9a489b3a4.png)

I'd suggest using _em_ unit  (or maybe `font-size: inherit;`, equivalent to 1em here) in [#a11y-outline { font-size: 0.9em)](https://github.com/xi/a11y-outline/blob/master/src/outline.scss#L19) would fix this problem because dialog is a direct descendant of body.

**Comment by xi** [comment]
I would advicate against such pratices and just learn to use px/em/rem properly, but I understand that this is just the way it is.

Thanks for the feedback!
