### ISSUE TITLE
Headings undefined

### ISSUE THREAD

**Issue by nico3333fr** [xi/a11y-outline#7]
Hi there,

first, thanks a lot for this extension, really cool (and it works with websites that have enabled CSP!).

I've tested it on some of my websites (https://www.nicolas-hoffmann.net/ and https://rocssti.net/en/), and I had a strange bug: the extension provides the correct outline, but says headings are undefined.

![undefined](https://user-images.githubusercontent.com/2578321/35519253-07800480-0514-11e8-9554-c265917cb5f5.png)

The only difference that I have with these two examples is that there are served as `application/xhtml+xml` (I don't know why it creates an issue to be honest).

Hope you will find a workaround!
Thanks a lot,
Nicolas

**Comment by xi** [comment]
Thanks for reporting the issue!

The issue seems to be that I did case-sensitive matching on tag names in the underlying library. This should be fixed with https://github.com/xi/aria-api/commit/bebd51a953ae052d84b59e7a0f4f30a65f3447fd.

I will try to publish the fixed version soon.
