### ISSUE TITLE
Feature Request: Please make it a 'proper' Chrome Extension

### ISSUE THREAD

**Issue by grahamarmfield** [xi/a11y-outline#8]
I think the extension is great, and can be really useful for testing a web page for how a screen reader user would experience landmarks, headings and links.

But the extension is also really useful for sighted keyboard users who can take advantage of the functionality. 

If such users are Chrome users, but are not deep level developers, your instructions for installing the Chrome extension would probably make no sense at all. I'm an occasional developer and I have to admit that they don't really make sense to me either.

**Comment by xi** [comment]
Adding anything to the chrome store requires you to pay money to google. I am not willing to do that.

What I can do is improve the installation instructions. Would it help if I published pre-build packages for each release?

**Comment by grahamarmfield** [comment]
Thanks for the response. I didn't realise you had to pay to put an app on the Chrome Store - so I can understand your point of view.

Anything that could make installing it easier would help - I'm thinking primarily for non-technical people, but also for me too.

**Comment by grahamarmfield** [comment]
Another thought...

If a keystroke user on Chrome can install the favlet (bookmarklet) version, then they can readily access the extension functionality on Chrome with just keystrokes. For Windows users the necessary keystrokes are:

1. **Ctrl + L** - to move to Location bar.
2. **F6** - to switch to bookmarks bar (it has to be visible already I think). This places keyboard focus on the first item in the bookmarks bar.
3. **Tab** (and **Shift + Tab**) - to move between your bookmarks.
4. **Enter** - to action the focused bookmark.

So if you place the favlet somewhere near the start of your bookmarks bar, then it's easy to get to.

Maybe if you put these steps in the Chrome section of your readme it would help? 

I'm afraid I don't know the corresponding keystrokes for Macs.

Cheers

**Comment by xi** [comment]
> If a keystroke user on Chrome can install the favlet (bookmarklet) version, then they can readily access the extension functionality on Chrome with just keystrokes.

I would like to not promote bookmarklets as they are a crude hack and will probably cease to work in the near future as content security policies are becoming more common.

I will think about ways to make the installation process in chrome simpler.

**Comment by xi** [comment]
I uploaded a pre-build bundle with the latest release and updated the installation instructions. This should make it much simpler to install in chrome.
