### ISSUE TITLE
Feature Request: Ignore <section> elements with no accessible name

### ISSUE THREAD

**Issue by grahamarmfield** [xi/a11y-outline#9]
On most pages, the extension finds the same list of landmarks as desktop screen readers like JAWS and NVDA. But on pages that feature <section> elements without an accessible name, these show up in the extension's list of landmarks as a series of regions, but not when using NVDA or JAWS.

An accessible name here is one that is provided by an '`aria-label`' or '`aria-labelledby`' or '`title`' attribute. See: [https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/landmarks/HTML5.html](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/landmarks/HTML5.html)

Examples:
`<section aria-label="My label"><h2>My heading<h2>` - should feature as: 'My label region'.

`<section aria-labelledby="sh"><h2 id="sh">My heading<h2>` - should feature as: 'My heading region'.

`<section><h2>My heading<h2>` - should **not** feature as a region.

To have plain regions listed in the extension doesn't really help anyone in my view.

**Comment by xi** [comment]
Thanks for the feedback! It is easy to miss these details as the information is spread across so many documents.

Fixes in https://github.com/xi/aria-api/commit/37dda6776322fb26557c2f7e9d1984a46b4ab272

**Comment by grahamarmfield** [comment]
Thanks for prompt action.
